### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by afaleq** [afaleq/ISQA3420-Group-Project#6]
This the presentation we will give in the class

**Comment by rjlucke** [comment]
I completely forgot to ask Matt about the powerpoint. :smile:

**Comment by Aljadani** [comment]
Working on the Presentation

**Comment by rjlucke** [comment]
[Group Presentation.pptx](https://github.com/afaleq/ISQA3420-Group-Project/files/31513/Group.Presentation.pptx)

**Comment by rjlucke** [comment]
[Group Presentation.pptx](https://github.com/afaleq/ISQA3420-Group-Project/files/31517/Group.Presentation.pptx)

**Comment by rjlucke** [comment]
Presentation slides embedded into Presentation.md
